### ISSUE TITLE
Unlink\Link GMaven project problem

### ISSUE THREAD

**Issue by grisha9** [grisha9/gmaven-plugin#12]
Sometimes the gmaven project does not unlink successfully. And it remains in the tool window. The problem is floating. Reproduced on OS Windows.

**Comment by grisha9** [comment]
@kriegaex Hi
I tried to reproduce this issue on Windows and it worked correctly for me. I added logs to version [233.27.1](https://plugins.jetbrains.com/plugin/22370-gmaven/edit/versions/beta) . If you have time, could you reproduce the problem again on version 233.27.1 and send me the IDE logs?

**Comment by kriegaex** [comment]
@grisha9, I sent the log to you via Telegram.

**Comment by grisha9** [comment]
fixed in 233.28
