### ISSUE TITLE
com.google.gson.Gson Error message when importing a project

### ISSUE THREAD

**Issue by yuryfunikov** [grisha9/gmaven-plugin#24]
GMaven version 242.4

![image](https://github.com/user-attachments/assets/24a172af-f4ec-41af-8724-8b26bb2d1565)

IntelliJ IDEA 2024.2.4 (Community Edition)
Build #IC-242.23726.103, built on October 23, 2024
Runtime version: 21.0.4+13-b509.26 amd64 (JCEF 122.1.9)
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Toolkit: sun.awt.X11.XToolkit
Linux 6.8.0-48-generic
Kotlin plugin: K2 mode (Beta)
GC: G1 Young Generation, G1 Concurrent GC, G1 Old Generation
Memory: 3984M
Cores: 12
Registry:
  analyze.exceptions.on.the.fly=true
  documentation.component.editor.font=true
  ide.experimental.ui=true
  i18n.locale=
Non-Bundled Plugins:
  com.supermaven.intellij (1.42)
  com.github.b3er.idea.plugins.arc.browser (0.32)
  PlantUML integration (7.11.2-IJ2023.2)
  ru.rzn.gmyasoedov.gmaven (242.4)
  ChatGPT (3.3.7-241.242)
Kotlin: 242.23726.103-IJ
Current Desktop: ubuntu:GNOME

**Comment by grisha9** [comment]
Maven central repository available? what version of Gson not found? Offline mode is disable?(maven -o parameter)    
What error in maven log? and process start parameters? like on screen  below:  
![image](https://github.com/user-attachments/assets/88dd4827-42ad-4481-b0b1-7421e1472769)

**Comment by grisha9** [comment]
Maven log result is success?   
![image](https://github.com/user-attachments/assets/22acad2b-3fdb-4b33-af82-c536654de3a2)

**Comment by grisha9** [comment]
maven-model-reader-plugin.jar was corrupted in local repo. After delete jar file in local repo all ok. Similar problem https://stackoverflow.com/questions/12364296/maven-failed-to-execute-goal-org-apache-maven-pluginsmaven-jar-plugin
